title: Nick Saia
email: nick@saia.me
description: > # Nick Saia's portfolio of design works.
baseurl: ""
url: ""
github_username: nsaia

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
permalink: pretty
